"""initial schema

Revision ID: e3eba316c2f3
Revises: None
Create Date: 2026-09-29 19:47:19.355387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector



# revision identifiers, used by Alembic.
revision: str = 'e3eba316c2f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('broker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_email'), 'broker', ['email'], unique=True)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_customer_id'), 'conversation', ['customer_id'], unique=False)
    op.create_table('listing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('carpet_area', sa.Numeric(), nullable=True),
    sa.Column('built_up_area', sa.Numeric(), nullable=True),
    sa.Column('plot_area', sa.Numeric(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("property_type IN ('flat', 'house_land')", name='ck_listing_property_type'),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_listing_location', 'listing', ['location'], unique=False, postgresql_using='gist')
    op.execute("CREATE INDEX IF NOT EXISTS idx_listing_location_geog ON listing USING gist (CAST(location AS geography));")
    op.create_index(op.f('ix_listing_broker_id'), 'listing', ['broker_id'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_customer_id'), 'lead', ['customer_id'], unique=False)
    op.create_index(op.f('ix_lead_listing_id'), 'lead', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_listing_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_customer_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_listing_broker_id'), table_name='listing')
    op.drop_index('idx_listing_location', table_name='listing', postgresql_using='gist')
    op.drop_table('listing')
    op.drop_index(op.f('ix_conversation_customer_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_broker_email'), table_name='broker')
    op.drop_table('broker')
    # ### end Alembic commands ###
